import { UserData } from "@/components/Types/UserData";

const DATA: UserData[] = [
  //"id":1,"email":"Pepe@gmail.com","name":"Pepe","lastName":"Perez","password":"1234","birthDate":"2025-09-28T16:55:45.204Z","phone":"1234","workRadius":null,"picture":"acaVaUnaURL"
  { id: 1, name: "Pepe", lastName: "Perez", profession: "Plomero", rating: 5, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Especialista en reparaciones y mantenimiento de cañerías y sistemas de agua." },
  { id: 2, name: "Facu", lastName: "Perez", profession: "Plomero", rating: 2.5, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Soluciona pérdidas, instalaciones y arreglos de plomería en general." },
  { id: 3, name: "Klos", lastName: "Perez", profession: "Plomero", rating: 3, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Experto en instalaciones sanitarias y reparaciones de cañerías." },
  { id: 4, name: "Nacho", lastName: "Perez", profession: "Plomero", rating: 4.9, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Atiende urgencias y realiza mantenimiento de sistemas de agua." },
  { id: 5, name: "Luca", lastName: "Perez", profession: "Electricista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Instalación y reparación de sistemas eléctricos residenciales y comerciales." },
  { id: 6, name: "Mari", lastName: "Perez", profession: "Electricista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Soluciona cortocircuitos y realiza mantenimiento eléctrico." },
  { id: 7, name: "Sofia", lastName: "Perez", profession: "Electricista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Especialista en instalaciones eléctricas y reparación de artefactos." },
  { id: 8, name: "Gaston", lastName: "Perez", profession: "Electricista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Realiza instalaciones, arreglos y mantenimiento eléctrico." },
  { id: 9, name: "Fran", lastName: "Perez", profession: "Gasista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Instalación y reparación de sistemas de gas y calefacción." },
  { id: 10, name: "Bauti", lastName: "Perez", profession: "Gasista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Especialista en conexiones y mantenimiento de gas domiciliario." },
  { id: 11, name: "Martu", lastName: "Perez", profession: "Gasista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Soluciona fugas y realiza instalaciones de gas seguras." },
  { id: 12, name: "Mati", lastName: "Perez", profession: "Gasista", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Mantenimiento y reparación de sistemas de gas y calefacción." },
  { id: 13, name: "Emi", lastName: "Perez", profession: "Limpieza", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Servicios de limpieza profesional para hogares y oficinas." },
  { id: 14, name: "Sol", lastName: "Perez", profession: "Limpieza", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Limpieza profunda y mantenimiento de espacios." },
  { id: 15, name: "Pili", lastName: "Perez", profession: "Pintor", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Pintura de interiores y exteriores, trabajos decorativos." },
  { id: 16, name: "More", lastName: "Perez", profession: "Pintor", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Especialista en pintura y renovación de ambientes." },
  { id: 17, name: "Juani", lastName: "Perez", profession: "Paseador", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Paseos y cuidado responsable de mascotas." },
  { id: 18, name: "Juanma", lastName: "Perez", profession: "Paseador", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Servicio de paseos diarios y atención personalizada para mascotas." },
  { id: 19, name: "Juanpi", lastName: "Perez", profession: "Entrenador", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Entrenamiento personalizado y rutinas de ejercicio." },
  { id: 20, name: "Joaco", lastName: "Perez", profession: "Entrenador", rating: 2, address: "Calle 1234", picture: require("./images/UsuarioPlaceHolder.png"), mail: "pepe@gmail.com", phoneNumber:"1111-2222", description: "Preparación física y asesoramiento deportivo." },
];

export default DATA;